// Register Reducer
export const EMAIL_REGISTER_CHANGED = 'EMAIL_REGISTER_CHANGED'
export const FULLNAME_REGISTER_CHANGED = 'USERNAME_REGISTER_CHANGED'
export const PASSWORD_REGISTER_CHANGED = 'PASSWORD_REGISTER_CHANGED'
export const CON_PASSWORD_REGISTER_CHANGED = 'CON_PASSWORD_REGISTER_CHANGED'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER = 'REGISTER_USER'

// LOGIN REDUCER
export const EMAIL_LOGIN_CHANGED = 'EMAIL_LOGIN_CHANGED'
export const PASSWORD_LOGIN_CHANGED = 'PASSWORD_LOGIN_CHANGED'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const LOGIN_USER = 'LOGIN_USER'


// AUTH REDUCER
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGOUT_USER = 'LOGOUT_USER'
export const NOT_LOGIN_YET = 'NOT_LOGIN_YET'
export const KEEP_LOGIN = 'KEEP_LOGIN'

// customer Reducer
export const SEARCH_BOX_CHANGE = 'SEARCH_BOX_CHANGE' 
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS'
export const SEARCH_FAIL = 'SEARCH_FAIL'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const CART_ADDED = 'CART_ADDED'
export const ADD = 'ADD'
export const REDUCE = 'REDUCE'